# Generated by Django 4.2.1 on 2023-07-08 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
                ('specialization', models.CharField(choices=[('p_general-practitioner', 'General Practitioner'), ('p_dentist', 'Dentist'), ('p_therapeutic-reflexologist', 'Therapeutic Reflexologist'), ('p_acoustician-hearing-aid', 'Acoustician (Hearing Aid)'), ('p_aesthetic-practitioner', 'Aesthetic Practitioner'), ('p_aesthetic-and-wellness', 'Aesthetic and Wellness'), ('p_allergy-specialist', 'Allergy Specialist'), ('p_anaesthesiologist', 'Anaesthesiologist'), ('p_anaesthetist', 'Anaesthetist'), ('p_audiologist', 'Audiologist'), ('p_baby-clinic', 'Baby Clinic'), ('p_biokineticist', 'Biokineticist'), ('p_cardiologist', 'Cardiologist'), ('p_chiropractor', 'Chiropractor'), ('p_clinic', 'Clinic'), ('p_clinical-haematologist', 'Clinical Haematologist'), ('p_clinical-neurophysiologist', 'Clinical Neurophysiologist'), ('p_clinical-nurse', 'Clinical Nurse'), ('p_clinical-pathologist', 'Clinical Pathologist'), ('p_clinical-practitioner', 'Clinical Practitioner'), ('p_clinical-psychologist', 'Clinical Psychologist'), ('p_clinical-services', 'Clinical Services'), ('p_clinical-social-worker', 'Clinical Social Worker'), ('p_clinical-technologist', 'Clinical Technologist'), ('p_clinical-technologist-pulmonology', 'Clinical Technologist - Pulmonology'), ('p_colon-hydrotherapist', 'Colon Hydrotherapist'), ('p_counselling-psychologist', 'Counselling Psychologist'), ('p_counsellor', 'Counsellor'), ('p_dental-surgeon', 'Dental Surgeon'), ('p_dental-therapist', 'Dental Therapist'), ('p_dentistry', 'Dentistry'), ('p_dermatologist', 'Dermatologist'), ('p_dietician', 'Dietician'), ('p_dietician-nutritionist', 'Dietician / Nutritionist'), ('p_doctor', 'Doctor'), ('p_ear-nose-throat-specialist', 'Ear, Nose & Throat Specialist'), ('p_educational-psychologist', 'Educational Psychologist'), ('p_endocrinologist', 'Endocrinologist'), ('p_family-physician', 'Family Physician'), ('p_family-practice', 'Family Practice'), ('p_forensic-psychologist', 'Forensic Psychologist'), ('p_functional-medicine-practitioner', 'Functional Medicine Practitioner'), ('p_gp', 'GP'), ('p_gastroenterologist', 'Gastroenterologist'), ('p_general-practice', 'General Practice'), ('p_general-surgeon', 'General Surgeon'), ('p_genetic-counsellor', 'Genetic Counsellor'), ('p_group-practice-multi-disciplinary', 'Group Practice: Multi Disciplinary'), ('p_gynaecologist', 'Gynaecologist'), ('p_hiv-clinician', 'HIV Clinician'), ('p_haematology', 'Haematology'), ('p_head-and-neck-surgeon', 'Head and Neck Surgeon'), ('p_health-and-wellness-coach', 'Health and Wellness Coach'), ('p_hearing-aid-acoustician', 'Hearing Aid Acoustician'), ('p_homeopath', 'Homeopath'), ('p_integrative-general-practitioner', 'Integrative General Practitioner'), ('p_integrative-medicine-practitioner', 'Integrative Medicine Practitioner'), ('p_interventional-radiologist', 'Interventional Radiologist'), ('p_lab-diagnostics', 'Lab Diagnostics'), ('p_life-coach', 'Life Coach'), ('p_live-blood-analysis-practitioner', 'Live Blood Analysis Practitioner'), ('p_live-blood-analyst', 'Live Blood Analyst'), ('p_marriage-counsellor', 'Marriage Counsellor'), ('p_maxillo-facial-and-oral-surgery', 'Maxillo Facial And Oral Surgery'), ('p_maxillofacial-surgeon', 'Maxillofacial Surgeon'), ('p_medical-oncologist', 'Medical Oncologist'), ('p_medical-technologist', 'Medical Technologist'), ('p_midwife', 'Midwife'), ('p_nephrologist', 'Nephrologist'), ('p_neurologist', 'Neurologist'), ('p_neuropsychologist', 'Neuropsychologist'), ('p_neurosurgeon', 'Neurosurgeon'), ('p_nurse', 'Nurse'), ('p_obstetrician', 'Obstetrician'), ('p_obstetrics-and-gynaecologist', 'Obstetrics And Gynaecologist'), ('p_occupational-health-nurse-practitioner', 'Occupational Health Nurse Practitioner'), ('p_occupational-health-physician', 'Occupational Health Physician'), ('p_occupational-practitioner', 'Occupational Practitioner'), ('p_occupational-therapist', 'Occupational Therapist'), ('p_oncologist', 'Oncologist'), ('p_ophthalmologist', 'Ophthalmologist'), ('p_optometrist', 'Optometrist'), ('p_oral-hygienist', 'Oral Hygienist'), ('p_orthodontist', 'Orthodontist'), ('p_orthopaedic-surgeon', 'Orthopaedic Surgeon'), ('p_orthotist-prosthetist', 'Orthotist & Prosthetist'), ('p_otolaryngologist', 'Otolaryngologist'), ('p_paediatric-dermatologist', 'Paediatric Dermatologist'), ('p_paediatric-general-practitioner', 'Paediatric General Practitioner'), ('p_paediatric-surgeon', 'Paediatric Surgeon'), ('p_paediatrician', 'Paediatrician'), ('p_periodontist', 'Periodontist'), ('p_physician', 'Physician'), ('p_physiotherapist', 'Physiotherapist'), ('p_plastic-surgeon', 'Plastic Surgeon'), ('p_podiatrist', 'Podiatrist'), ('p_primary-care-physician', 'Primary Care Physician'), ('p_primary-healthcare-clinic', 'Primary Healthcare Clinic'), ('p_primary-healthcare-nurse', 'Primary Healthcare Nurse'), ('p_prosthodontist', 'Prosthodontist'), ('p_psychiatrist', 'Psychiatrist'), ('p_psychologist', 'Psychologist')], default='', max_length=50)),
                ('qualifications', models.CharField(default='', max_length=200)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('contact_number', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(default='', max_length=100)),
                ('biography', models.TextField(default='')),
                ('languages_spoken', models.CharField(default='', max_length=100)),
                ('hospital_affiliations', models.CharField(default='', max_length=200)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='doctor_profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('medical_conditions', models.TextField(default='')),
                ('surgeries', models.TextField(default='')),
                ('medications', models.TextField(default='')),
                ('allergies', models.TextField(default='')),
                ('occupation', models.CharField(default='', max_length=100)),
                ('exercise_habits', models.CharField(default='', max_length=100)),
                ('dietary_restrictions', models.CharField(default='', max_length=100)),
                ('family_medical_history', models.TextField(default='')),
                ('age', models.PositiveIntegerField(default=0)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=3)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='nothing', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
