# Generated by Django 4.2.1 on 2023-07-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='state',
            field=models.CharField(default='AZ', max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='zip_code',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
