# Generated by Django 4.2.1 on 2023-07-15 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_patientprofile_city_patientprofile_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencycontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('relation', models.CharField(default='Unknown', max_length=200)),
                ('Contact', models.CharField(default='Unknown', max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.patientprofile')),
            ],
        ),
    ]
