# Generated by Django 4.2.1 on 2023-07-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insuranceininfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insurancecarrier', models.CharField(default='Unknown', max_length=200)),
                ('plan', models.CharField(default='Unknown', max_length=200)),
                ('Contact', models.CharField(default='Unknown', max_length=200)),
                ('policynumber', models.CharField(default='Unknown', max_length=200)),
                ('groupnumber', models.CharField(default='Unknown', max_length=200)),
                ('socialsecuritynumber', models.CharField(default='Unknown', max_length=200)),
                ('patient', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Registration.patientprofile')),
            ],
        ),
    ]
