# Generated by Django 4.2.1 on 2023-07-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_insuranceininfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceininfo',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Emergencycontact',
        ),
        migrations.DeleteModel(
            name='Insuranceininfo',
        ),
    ]
