# Generated by Django 4.2.1 on 2023-07-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthfinda', '0002_remove_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(default='Nothing'),
        ),
    ]
