# Generated by Django 4.2.1 on 2023-07-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
        ('healthfinda', '0003_appointment_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nothing', max_length=1000)),
                ('message', models.TextField(default='Nothing')),
                ('timestamp', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.doctorprofile')),
            ],
        ),
    ]
