# Generated by Django 4.2.1 on 2023-07-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthfinda', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
